skip_prep: False

seed: 1986

# generated data splits, checkpoints, etc
data_folder: /data/voxdata

# voxceleb data folders will be scanned and all the found waves, id, lengths saved here
# saves time on future runs
voxceleb_file_info: !ref <data_folder>/file_info.pkl

output_folder: !ref /data/voxdata/results/<seed>
save_folder: !ref <output_folder>/save


# Folders for VoxCeleb1 and VoxCeleb2. Data needs to be pre-downloaded and converted into wav
data_folder_voxceleb1: /data/voxceleb1
data_folder_voxceleb2: /data/voxceleb2

splits: [train, dev, test]

test_pairs_in_file: /data/voxceleb1/list_test_all2.txt
# random verification pairs to use from input file. Remove/set to None for full
test_pairs_out_file: !ref <data_folder>/verification.txt

verification_file: !ref <data_folder>/verification.txt

# number of unique speakers to use (before split)
speaker_quantity: 100

# number of random test pairs to use from verification_file
test_pairs_quantity: 100

# how should data be split between train/valid
split_ratio: 90

train_data: !ref <data_folder>/train.csv
valid_data: !ref <data_folder>/valid.csv

# Data files for verification after training. Speakers here will not be included in train/valid split
# enrol and test utterances data is created based on verification_file
enrol_data: !ref <data_folder>/enrol.csv
test_data: !ref <data_folder>/test.csv

# Folder to extract data augmentation files
rir_folder: !ref /data/rirs_noises

# Feature parameters
n_mels: 80
left_frames: 0
right_frames: 0
deltas: False

sample_rate: 16000
sentence_len: 3.0 # in seconds
amp_th: 0.0005 # 5e-04
